pipelines:
  custom:
    build:
      - step:
          name: Test the build
          image: ruby:latest
          script:
            - git submodule init
            - git submodule update
            - bundle install
            - gem install html-proofer
            - bundle exec jekyll build -d _site/datadriven/
            - htmlproofer ./_site --url-ignore "/#.*/" --file-ignore /datadriven/reveal.js/
  branches:
    master:
      - step:
          name: Deploy to Github repo
          deployment: production
          script:
            - git remote add github $GITHUB_REPO_URL
            - git push github $GITHUB_REPO_BRANCH